name: Vulnerability Scanner

on:
  push:
    branches:
      - dev

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run vulnerability scanner
        run: |
          python vulnerability_scanner.py
